# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.1
delay: 0.0
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "abdomen", "chest", "head", "hip", "lButtock", 
  "lCollar", "lFoot", "lForeArm", "lHand", "lShin",
  "lShldr", "lThigh", "neck", "rButtock", "rCollar",
  "rFoot", "rForeArm", "rHand", "rShin", "rShldr",
  "rThigh"
]
joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2
]

joint_a_max: [
  20, 20, 25, 20, 20, 
  20, 30, 50, 50, 30,
  50, 30, 25, 20, 20,
  30, 50, 50, 30, 50, 
  30
]
# All values are in the 95% Quantiles defined in DIN 33402-2
# There are no values about arm circumfence, so we take the leg values as overapproximation.
bodies:
  - name: "lUpperArm" 
    proximal: "lShldr"
    distal: "lForeArm"
    thickness: 0.2
    max_contact_energy_unconstrained: 0.25

  - name: "lLowerArm"
    proximal: "lForeArm"
    distal: "lHand"
    thickness: 0.132
    max_contact_energy_unconstrained: 0.5

  - name: "lHand"
    proximal: "lHand"
    distal: "lHand"
    thickness: 0.206
    max_contact_energy_unconstrained: 0.5

  - name: "rUpperArm" 
    proximal: "rShldr"
    distal: "rForeArm"
    thickness: 0.2
    max_contact_energy_unconstrained: 0.25

  - name: "rLowerArm"
    proximal: "rForeArm"
    distal: "rHand"
    thickness: 0.132
    max_contact_energy_unconstrained: 0.5

  - name: "rHand"
    proximal: "rHand"
    distal: "rHand"
    thickness: 0.206
    max_contact_energy_unconstrained: 0.5

  - name: "torso"
    proximal: "hip"
    distal: "neck"
    thickness: 0.434
    max_contact_energy_unconstrained: 0.25
  
  - name: "head"
    proximal: "head"
    distal: "head"
    thickness: 0.434
    max_contact_energy_unconstrained: 0.1

extremities:
  - name: "lArm"
    base: "lShldr"
    end: "lHand"
    length: 1.0 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0
    max_contact_energy_unconstrained: 0.1  # Head value needed here.
    
  - name: "rArm"
    base: "rShldr"
    end: "rHand"
    length: 1.0 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0
    max_contact_energy_unconstrained: 0.1  # Head value needed here.