# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.0
delay: 0.0
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: false

# Names of joints in correct outputted order
joint_names: [
  "head"
]
joint_v_max: [
  1
]

joint_a_max: [
  10
]

bodies:
  - name: "head" 
    proximal: "head"
    distal: "head"
    thickness: 0.1
    max_contact_energy_unconstrained: 0.2

extremities: