# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.1
delay: 0.0
use_kalman_filter: true
s_w: 2.0e+2
s_v: 1.0e-6
initial_pos_var: 0.003
initial_vel_var: 0.5

use_combined_model: true

# Names of joints in correct outputted order
joint_names: [
  "L_Hip", "R_Hip", "Torso", "L_Knee", "R_Knee",
  "Spine", "L_Ankle", "R_Ankle", "Chest", "L_Toe",
  "R_Toe", "Neck", "L_Thorax", "R_Thorax", "Head",
  "L_Shoulder", "R_Shoulder", "L_Elbow", "R_Elbow", "L_Wrist",
  "R_Wrist", "L_Hand", "R_Hand"
]

joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2
]

joint_a_max: [
  20, 20, 20, 30, 30,
  25, 30, 30, 20, 30,
  30, 25, 25, 25, 25,
  50, 50, 50, 50, 50,
  50, 50, 50
]

bodies:
  - name: "L_UpperArm" 
    proximal: "L_Shoulder"
    distal: "L_Elbow"
    thickness: 0.2 # 95 percentile of upper leg diameter according to DIN 33402-2:2020-12 (There is no information on upper arm diameter.)
    max_contact_energy_unconstrained: 0.25

  - name: "L_LowerArm"
    proximal: "L_Elbow"
    distal: "L_Wrist"
    thickness: 0.132 # 95 percentile of lower leg diameter according to DIN 33402-2:2020-12 (There is no information on lower arm diameter.)
    max_contact_energy_unconstrained: 0.5

  - name: "L_Hand"
    proximal: "L_Wrist"
    distal: "L_Hand"
    thickness: 0.206 # 95 percentile of hand length according to DIN 33402-2:2020-12
    max_contact_energy_unconstrained: 0.5

  - name: "R_UpperArm" 
    proximal: "R_Shoulder"
    distal: "R_Elbow"
    thickness: 0.2 # 95 percentile of upper leg diameter according to DIN 33402-2:2020-12 (There is no information on upper arm diameter.)
    max_contact_energy_unconstrained: 0.25

  - name: "R_LowerArm"
    proximal: "R_Elbow"
    distal: "R_Wrist"
    thickness: 0.132 # 95 percentile of lower leg diameter according to DIN 33402-2:2020-12 (There is no information on lower arm diameter.)
    max_contact_energy_unconstrained: 0.5

  - name: "R_Hand"
    proximal: "R_Wrist"
    distal: "R_Hand"
    thickness: 0.206 # 95 percentile of hand length according to DIN 33402-2:2020-12
    max_contact_energy_unconstrained: 0.5

  - name: "Torso"
    proximal: "Torso"
    distal: "Neck"
    thickness: 0.434 # Lays in 95% of Shoulder width according to DIN 33402-2:2020-12
    max_contact_energy_unconstrained: 0.5
  
  - name: "Head"
    proximal: "Neck"
    distal: "Head"
    thickness: 0.434 # Lays in 95% of Shoulder width according to DIN 33402-2:2020-12
    max_contact_energy_unconstrained: 0.1

extremities:
  - name: "L_Arm"
    base: "L_Shoulder"
    end: "L_Hand"
    length: 0.825 # 95 percentile of reach to the front according to DIN 33402-2:2020-12
    thickness: 0.0
    max_contact_energy_unconstrained: 0.1  # Head value needed here.
    
  - name: "R_Arm"
    base: "R_Shoulder"
    end: "R_Hand"
    length: 0.825 # 95 percentile of reach to the front according to DIN 33402-2:2020-12
    thickness: 0.0
    max_contact_energy_unconstrained: 0.1  # Head value needed here.