robot_name: Kinova3

nb_joints: 7

secure_radius: 0.02

transformation_matrices: [
#shoulder_link
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -1.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.1564, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#HalfArm1_Link
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.0054, 
    0.0000, 1.0000, -0.0000, -0.1284, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#HalfArm2_Link
    1.0000, -0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, -0.2104, 
    -0.0000, -1.0000, -0.0000, -0.0064, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#forearm_link
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.0064, 
    0.0000, 1.0000, -0.0000, -0.2104, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#SphericalWrist1_Link
    1.0000, -0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, -0.2084, 
    -0.0000, -1.0000, -0.0000, -0.0064, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#SphericalWrist2_Link
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.0002, 
    0.0000, 1.0000, -0.0000, -0.1059, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#Bracelet_Link
    1.0000, -0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, -0.1059, 
    -0.0000, -1.0000, -0.0000, -0.0002, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
]
enclosures: [
    0.00006670, 0.01283162, -0.02638818,
    -0.00006670, -0.01283162, -0.14361182,
    0.06431349,
    ###
    0.00000116, 0.03413609, -0.02437341,
    -0.00000116, -0.20413609, 0.00437341,
    0.06006811,
    ###
    0.00018533, 0.00823512, -0.03033981,
    -0.00018533, -0.00823512, -0.22966018,
    0.06045311,
    ###
    0.00007166, -0.19429687, -0.00258290,
    -0.00007166, 0.02429686, -0.02741710,
    0.05039166,
    ###
    0.00510265, 0.00737492, -0.02673512,
    0.00489735, -0.01737493, -0.11326489,
    0.05236214,
    ###
    0.00024090, -0.08739071, 0.00593931,
    -0.00024090, 0.00739072, -0.02593932,
    0.05633688
]
