robot_name: siciliano

nb_joints: 3

secure_radius: 0

transformation_matrices: [
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1,
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1,
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1
]

enclosures: [
  0, 0, 0,
  1, 0, 0,
  1,
  1, 0, 0,
  2, 0, 0,
  1,
  2, 0, 0,
  3, 0, 0,
  1
]