robot_name: UR5e

nb_joints: 6

secure_radius: 0.02

transformation_matrices: [
#Shoulder_pan_joint
	1.0000, 0.0000, 0.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, 0.0000, 
	0.0000, 0.0000, 1.0000, 0.1630, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
#Shoulder_lift_joint
	0.0000, 0.0000, 1.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, 0.1380, 
	-1.0000, 0.0000, 0.0000, 0.0000, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
#elbow_joint
	1.0000, 0.0000, 0.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, -0.1310, 
	0.0000, 0.0000, 1.0000, 0.4250, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
#wrist_1_joint
	0.0000, 0.0000, 1.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, 0.0000, 
	-1.0000, 0.0000, 0.0000, 0.3920, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
#wrist_2_joint
	1.0000, 0.0000, 0.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, 0.1270, 
	0.0000, 0.0000, 1.0000, 0.0000, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
#wrist_3_joint
	1.0000, 0.0000, 0.0000, 0.0000, 
	0.0000, 1.0000, 0.0000, 0.0000, 
	0.0000, 0.0000, 1.0000, 0.1000, 
	0.0000, 0.0000, 0.0000, 1.0000, 
	### 
]
enclosures: [
0.00000465, 0.00714876, 0.00382337,
0.00000465, 0.00714876, 0.00382337,
0.09397281,
###
0.00031387, 0.00486244, 0.00114070,
-0.00031699, -0.01079706, 0.42284959,
0.09081816,
###
-0.00029730, 0.01342908, -0.01859868,
0.00054018, -0.01643743, 0.39131386,
0.07945086,
###
0.00000731, 0.10953390, -0.00135434,
0.00000731, 0.10953390, -0.00135434,
0.07694063,
###
0.00007969, 0.01511643, 0.09446009,
-0.00007591, -0.01870569, 0.09792996,
0.05669725,
###
0.00065674, 0.07622904, 0.00770268,
-0.00050915, 0.07587573, -0.00222284,
0.04439946
]
