robot_name: Panda

nb_joints: 7

secure_radius: 0.02

transformation_matrices: [
    1, 0, 0, 0, 
    0, 1, 0, 0, 
    0, 0, 1, 0, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, 0, 
    0, 1, 0, 0, 
    0, 0, 1, 0.333, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, 0, 
    0, -3.4915e-15, 1, 0, 
    0, -1, -3.4915e-15, 0, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, 0, 
    0, -3.4915e-15, -1, -0.316, 
    0, 1, -3.4915e-15, -1.1033e-15, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, 0.0825, 
    0, -3.4915e-15, -1, 0, 
    0, 1, -3.4915e-15, 0, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, -0.0825, 
    0, -3.4915e-15, 1, 0.384, 
    0, -1, -3.4915e-15, -1.3407e-15, 
    0, 0, 0, 1, 
    ### 
    1, 0, 0, 0, 
    0, -3.4915e-15, -1, 0, 
    0, 1, -3.4915e-15, 0, 
    0, 0, 0, 1]  

tool_transformation_matrix: [
    1, 0, 0, 0.088, 
    0, -3.4915e-15, -1, 0, 
    0, 1, -3.4915e-15, 0, 
    0, 0, 0, 1, 
    ### 
    ]

enclosures: [

    -0.041271, -0.000011589, 0.07,
    -0.041271, -0.000011589, 0.07,
    0.13543,
    ###
    -0.00051881, -0.0087363, -0.10336,
    0.00050531, -0.065641, -0.033639,
    0.11001,
    ###
    -0.0010678, -0.10457, 0.0090334,
    0.0010409, -0.034405, 0.065357,
    0.11047,
    ###
    0.0041991, -0.002757, -0.059555,
    0.078286, 0.058808, -0.0064428,
    0.08591,
    ###
    -0.078018, 0.061892, -0.0023521,
    -0.0044925, 0.0071085, 0.058416,
    0.086403,
    ###
    0.000076664, -0.0084762, -0.20335,
    -0.000094564, 0.083416, -0.0034559,
    0.084915,
    ###
    0.042058, 0.015232, 0.006132,
    0.042058, 0.015232, 0.006132,
    0.11214]
