robot_name: IIWA

nb_joints: 7

secure_radius: 0.02

transformation_matrices: [
#link_1
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, 1.0000, 0.0000, 0.0000, 
    0.0000, 0.0000, 1.0000, 0.1500, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_2
    -1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, 0.0000, 
    0.0000, 1.0000, -0.0000, 0.1900, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_3
    -1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, 0.2100, 
    0.0000, 1.0000, -0.0000, 0.0000, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_4
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.0000, 
    0.0000, 1.0000, -0.0000, 0.1900, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_5
    -1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, 0.2100, 
    0.0000, 1.0000, -0.0000, 0.0000, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_6
    1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, -1.0000, 0.0607, 
    0.0000, 1.0000, -0.0000, 0.1900, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ### 
#link_7
    -1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -0.0000, 1.0000, 0.0810, 
    0.0000, 1.0000, -0.0000, 0.0607, 
    0.0000, 0.0000, 0.0000, 1.0000, 
    ###
]


tool_transformation_matrix: [

#right_hand
    -1.0000, 0.0000, 0.0000, 0.0000, 
    0.0000, -1.0000, 0.0000, 0.0000, 
    0.0000, 0.0000, 1.0000, 0.0440, 
    0.0000, 0.0000, 0.0000, 1.0000
    ]

enclosures: [

    -0.00002354, -0.04254148, 0.18096623,
    0.00002354, 0.00254148, 0.05903377,
    0.09564619,
    ###
    0.00107843, 0.15499322, 0.01955847,
    -0.00107843, -0.04499322, 0.02044153,
    0.09534337,
    ###
    0.00006741, 0.04786947, 0.22057621,
    -0.00006741, -0.00786948, 0.04942380,
    0.09435929,
    ###
    0.00103875, 0.15499347, 0.01953003,
    -0.00103875, -0.04499346, 0.02046997,
    0.09530783,
    ###
    0.00014995, -0.00738485, 0.08529100,
    -0.00014995, 0.03738485, 0.17470902,
    0.11691446,
    ###
    0.00000000, 0.00000000, 0.06000000,
    0.00000000, 0.00000000, 0.06000000,
    0.09899495,
    ###
    0.00000000, 0.00000000, 0.02000000,
    0.00000000, 0.00000000, 0.02000000,
    0.06164414
    ]
